version: "3.8"

services:
  hasura:
    image: hasura/graphql-engine:v2.25.1
    ports:
      - "127.0.0.1:3000:8080"
    depends_on:
      - db
      - db-dex
      - db-metadata
    restart: always
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, websocket-log, query-log
      - HASURA_GRAPHQL_LOG_LEVEL=warn
      - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-qwerty}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
      - HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS=true
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-qwerty}@db:5432/dipdup
      - HASURA_GRAPHQL_PG_CONNECTIONS=20

  db:
    image: postgres:15.3
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5002:5432
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dipdup" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-dex:
    image: postgres:15.3
    volumes:
      - db-dex:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5003:5432
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dipdup" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-metadata:
    image: postgres:15.3
    volumes:
      - db-metadata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5004:5432
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dipdup" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
  db-dex:
  db-metadata:
